### ISSUE TITLE
Add citation information for algorithms

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#578]
See the minimal example from the citation file format:

```
cff-version: 1.0.3
message: If you use this software, please cite it as below.
authors:
  - family-names: Druskat
    given-names: Stephan
    orcid: https://orcid.org/0000-0003-4925-7248
title: My Research Tool
version: 1.0.4
doi: 10.5281/zenodo.1234
date-released: 2017-12-18
```

https://citation-file-format.github.io/

Requires:
- [ ] Orcid field on users profiles

Version, title and date can be automatically generated. Where to get a DOI from?
